### ISSUE TITLE
Move/Drag popup should showup before first click and do both clicks if ENTER is pressed (gooood luck)

### ISSUE THREAD

**Issue by james-bern** [james-bern/CS3XX#104]

**Comment by NathanVosburg** [comment]
very scuffed fix for move by overriding first click when enter is pressed. currently the draw preview doesnt work but will fix soon

**Comment by NathanVosburg** [comment]
draw preview fixed for move but still have drag todo

**Comment by NathanVosburg** [comment]
moving to alpha

**Comment by NathanVosburg** [comment]
just fixed it for drag, still no drag preview but that is more an issue for #96
