### ISSUE TITLE
Removing zero length entities automatically (messagef when the ZeroLengthEntityRemover instance finds one)

### ISSUE THREAD

**Issue by james-bern** [james-bern/CS3XX#105]

**Comment by NathanVosburg** [comment]
just implemented. the message is sent by the ZeroLengthEntityRemoverMessagerNotificationManager after the ZeroLengthEntityRemoverEntityLengthDetector detects a zero length line that is removed by an instance of a ZeroLengthEntityRemoverWorkerRemover (these are managed by the ZeroLengthEntityRemoverSupremeInstanceManager so we shouldn't worry about zero length entities)

**Comment by james-bern** [comment]
🥲 I am so proud
