### ISSUE TITLE
save dxf

### ISSUE THREAD

**Issue by james-bern** [james-bern/CS3XX#15]
- [x] save dxf
- [x] prompt y/n if already exists (??)
> - [x] save currently opened file in state to allow for fast save w/ no confirmation 
> - [ ] some sort of save vs save as do user doesn't have to retype filename
- [ ] losing current project progress whenever app is closed? 
> - [ ] some sort of auto save or warning?

**Comment by NathanVosburg** [comment]
what is good behaviour for quicksave when there are potentially two differnt files open? 
individual quicksave hotkeys, quicksave both, ask which one to save?

**Comment by james-bern** [comment]
Hmm…I do not know 🙃 I think…maybe two questions:
- What’s a reasonable choice for alpha?
- Where do we envision things maybe heading for beta?

For alpha, it seems like the three possible Save (Export) commands are
SaveDXF (SaveDrawing) SaveSTL (SaveMesh) and SaveAll (SaveBoth). We could
support all three, and have buttons for at least DXF and STL. We could also
have corresponding Load buttons for DXF and STL. We might need to
understand our users better to make an informed decision.

There is also the Save vs. Save As… question. (Currently we just have a
very aggressive Save As…; ZBrush, for example, only has a less aggressive
Save As…; Word and a lot of other programs have both Save and Save As…)

It also might be worth thinking outside the box a bit, about, for example
auto-saves, native file open dialogue, etc. We don’t actually have to do
these, but it might be informative to imagine the ideal load+save setup for
alpha.

For beta, it seems like the user might have several meshes open at once,
and maybe the notion of a “session” becomes meaningful. This gets really
hazy for me, but is also probably worth thinking about 🙂👍

Woo!
Jim
