### ISSUE TITLE
consider adding the kitchen sink test to a hotkey or similar or just having something that makes it so we don't forget to test it

### ISSUE THREAD

**Issue by james-bern** [james-bern/CS3XX#181]

**Comment by NathanVosburg** [comment]
great idea. it has probably been a couple months since i last tested kitchen sink. it is very easy to forget that it exists

**Comment by james-bern** [comment]
`CONTROL + SHIFT + K` now aggressively runs the kitchen sink test (the double mouse bump is correct i think; there are two calls to SetAxis)
