### ISSUE TITLE
revolve tween (almost done)

### ISSUE THREAD

**Issue by james-bern** [james-bern/CS3XX#182]
maybe something like this https://glbook.gamedev.net/GLBOOK/glbook.gamedev.net/moglgp/advclip.html

**Comment by NathanVosburg** [comment]
NOTE: dxf_axis_angle_y is in radians, not sure how many remnants in codebase are still radians. decided not to fix because we are moving to turns soon™

**Comment by NathanVosburg** [comment]
TODO: make work when total angle > 360

**Comment by NathanVosburg** [comment]
consolidating with #138 because main issue for both is drawing the clip plane
