### ISSUE TITLE
RCopy and similar need to be bulletproofed (try typing 9999 for the number of copies 💀)

### ISSUE THREAD

**Issue by james-bern** [james-bern/CS3XX#185]

**Comment by NathanVosburg** [comment]
even though there is no animation setting the copy field to 1000 significant lab

**Comment by NathanVosburg** [comment]
quick fix for rcopy and copy is setting copy cap to 180 which seems like a reasonable limit

**Comment by NathanVosburg** [comment]
the draw previews both lcopy and rcopy do a eso_start/end for every entity which doesnt seem ideal and was the amin cause of lag (stew????) making new issue for this
