### ISSUE TITLE
snapping to entity (while drawing line) sometimes changes its color back to green

### ISSUE THREAD

**Issue by james-bern** [james-bern/CS3XX#41]

**Comment by NathanVosburg** [comment]
Can you provide an example of this? I haven't been able to replicate

**Comment by james-bern** [comment]
Oh I think it’s like…when divide on snap is turned on maybe? It’ll be easy
to fix later if it’s still an issue 🙂👍

**Comment by NathanVosburg** [comment]
ohhh i think i fixed this a bit ago, arcs did not look for entity color.
