### ISSUE TITLE
(nate working on) config needs inches vs. mm

### ISSUE THREAD

**Issue by NathanVosburg** [james-bern/CS3XX#59]

**Comment by NathanVosburg** [comment]
what are conversation's default units?

**Comment by james-bern** [comment]
so…i think right now it does the following things related to units
- scales by 25.4 on open dxf
- scales by 1/25.4 to save dxf
- ??? on load/dave stl
- messages “mm” in a variety of places (Measure, Extrude, etc.)

but none of those were deliberate decisions; i think they just follow from
“omax saves/opens in inches and Jim works in mm”

you might want to reimagine all this from scratch

some people work in mm (me), but a lot of people (most Americans?—including
my friend John) work in inches

-Jim

**Comment by james-bern** [comment]
note that the original pre-alpha work flow of conversation was students
drawing in omax and then extruding in conversation, but now we expect users
to really just be in conversation
