### ISSUE TITLE
(nate working on) config needs bool to hide gui

### ISSUE THREAD

**Issue by NathanVosburg** [james-bern/CS3XX#60]

**Comment by NathanVosburg** [comment]
im going to implement a basic version of this but i think it would be good to discuss how we want the config file to be structured syntactically

**Comment by james-bern** [comment]
I like the current structure! 🙂👍
NAME=VALUE
very simple cannot fail

**Comment by james-bern** [comment]
INCLUDE_CLOUDSTRIKE=TRUE

**Comment by NathanVosburg** [comment]
ill need you to get an spc signature but ill get the kernel driver ready
