### ISSUE TITLE
tangent snap

### ISSUE THREAD

**Issue by NathanVosburg** [james-bern/CS3XX#66]
- [x] random?? snap to origin sometimes
- [x] divide entity at first snap of tangent
- [x] make tan-tan snap fixed
- [x] tan start
- [x] tan end

**Comment by NathanVosburg** [comment]
this one is going to be really weird because it doesnt actually know where to snap to until the second click

**Comment by james-bern** [comment]
i’m sure with a big enough macro in commands.cpp there will technically be
no special cases

**Comment by NathanVosburg** [comment]
alright then you can have fun with this one that sounds terrifying

**Comment by NathanVosburg** [comment]
sometime soon the entire codebase will just be inside the commands macro

**Comment by NathanVosburg** [comment]
wow what a perfect tangent snap im sure there is nothing weird about it whatsoever
