### ISSUE TITLE
TODO: sc needs work (see sc.dxf)

### ISSUE THREAD

**Issue by james-bern** [james-bern/CS3XX#77]
also if there are three entities at an intersection it only selects two to path through

**Comment by NathanVosburg** [comment]
honestly i dont think this will come up too much as it already works about as well as layout's which is kinda wack. unless there is a very fast fix i suggest push to beta

**Comment by NathanVosburg** [comment]
fixed for most cases

TODO:
- [ ] increase bucket size (will need to use recursion or queue to handle branches)
- [ ] doesnt work for two circles in glorbo.dxf for some reason

**Comment by NathanVosburg** [comment]
select connected is fixed but am waiting to merge because it will have to be integrated into the circle changes

**Comment by james-bern** [comment]
Oh you should be good to merge! I’ll try to add the circle stuff in a way
that doesn’t break too much
