### ISSUE TITLE
CIRCLE entity type

### ISSUE THREAD

**Issue by james-bern** [james-bern/CS3XX#92]
things that currently dont work with circle

- [ ] snaps
    - [x] perp
    - [ ] intersection (this is more an issue with closest_intersection() but will leave unchecked until fixed)
- [x] fillet
- [x] dogear
- [x] mirror
- [x] drag
- [ ] helper functions
     - [ ] intersections

**Comment by NathanVosburg** [comment]
should be done (??????)
